#
# Docker container definition
#
version: '2'
services:
  #
  # haveged deployment
  #
  haveged:
    privileged: true
    image: picoded/haveged
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: no-haveged=true,no-essential=true
      io.rancher.scheduler.global: 'true'