#
# Catalog options configuration
#
.catalog:
  name: "essential"
  version: "v1.0.0"
  description: "Essential docker containers, that should run with every instance"
  minimum_rancher_version: v0.9.0
  uuid: picoded-essential-0
#
# Actual service definition
#
version: '2'
services:
  haveged:
    start_on_create: true
  logrotate:
    start_on_create: true
