#
# Catalog options configuration
#
.catalog:
  name: "multibeat to elasticsearch"
  version: "v1.1.0"
  description: "Elasticsearch proxy gateway, its main use case is to provide a proxy for AWS elasticsearch"
  minimum_rancher_version: v0.9.0
  uuid: es-multibeat-0
  questions:
    #
    # Elasticsearch endpoint for AWS
    #
    - variable: "es_host"
      label: "Elasticsearch host:"
      description: "Elasticsearch host to connect to, when possible avoid hostname with heavy DNS queries"
      default: ''
      required: true
      type: "string"
    #
    # Elasticsearch protocall for target
    #
    - variable: "es_prot"
      label: "Elasticsearch HTTP(S) Protocall:"
      description: "http / https only"
      default: 'http'
      required: true
      type: "string"
    #
    # Elasticsearch port for AWS
    #
    - variable: "es_port"
      label: "Elasticsearch Port:"
      description: "80 / 443 / 9200"
      default: '9200'
      required: true
      type: "string"
    #
    # HTTP Auth user for auth layer elasticsearch
    #
    - variable: "es_user"
      label: "Elasticsearch Username:"
      description: "The elasticsearch user"
      default: 'elasticsearch'
      type: "string"
    #
    # HTTP Auth pass for auth layer elasticsearch
    #
    - variable: "es_pass"
      label: "Elasticsearch Password:"
      description: "The elasticsearch password"
      default: 'SeriouslyChangeThisToSomeRandomlyGeneratedPassword'
      type: "string"
    #
    # Metricbeat index to store in
    #
    - variable: "metricbeat_index_prefix"
      label: "Metricbeat index prefix:"
      description: "Metric index prefix, note that -%{+yyyy.MM.dd} will be appended"
      default: 'metricbeat'
      required: true
      type: "string"
    #
    # Metricbeat index to store in
    #
    - variable: "filebeat_index_prefix"
      label: "Filebeat index prefix:"
      description: "Logging index prefix, note that -%{+yyyy.MM.dd} will be appended"
      default: 'logbeat'
      required: true
      type: "string"
    #
    # labels to AVOID deployment to
    #
    - variable: "metric_period"
      label: "Metric interval/period:"
      description: "Frequency in which metric is collected, note that file system is fixed to 1m interval regardless"
      default: '10s'
      required: true
      type: "string"
    #
    # labels to AVOID deployment to
    #
    - variable: "host_avoidlabel"
      label: "Deployment Log Server rancher Label:"
      description: "labels to AVOID deployment"
      default: 'no-multibeat=true, multibeat=false'
      required: true
      type: "string"
#
# Actual service definition
#
version: '2'
services:
  docker-metricbeat:
    start_on_create: true