# Name of the Catalog Entry
name: "GitLab"
# Description of the Catalog Entry
description: "Simple self contained gitlab installation"
# Version of the Catalog to be used
version: "v1.0.0"
# Category to be used for searching catalog entries
category: picoded gitlab
# The maintainer of the catalog entry
maintainer: eugene@picoded.com
# The license
license: GPL Version 3
# A URL related to the catalog entry
projectURL: https://github.com/picoded/rancher-catalog
