#
# Docker container definition
#
version: '2'
services:
  gce-docker:
    privileged: true
    image: mcuadros/gce-docker
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /run/docker/plugins:/run/docker/plugins
    - /:/rootfs
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: gce-docker=false
      io.rancher.scheduler.global: 'true'
