version: '2'
services:
  public-HTTPS:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 443:443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: public-loadbalancer=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  traefik-conf:
    image: rawmind/rancher-traefik:1.3.3
    network_mode: none
    volumes:
    - /opt/tools
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: public-loadbalancer=true
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
  public-HTTP:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  traefik:
    image: rawmind/alpine-traefik:1.3.3
    environment:
      CONF_INTERVAL: '20'
      TRAEFIK_HTTPS_ENABLE: 'false'
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_INSECURE_SKIP: 'false'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_HEALTHCHEK: 'false'
    stdin_open: true
    tty: true
    volumes_from:
    - traefik-conf
    labels:
      io.rancher.scheduler.affinity:host_label: public-loadbalancer=true
      io.rancher.sidekicks: traefik-conf
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  hello-world:
    image: picoded/hello-world
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: public-loadbalancer=true
  https-307-redirect:
    image: picoded/https-redirect
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: public-loadbalancer=true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
